// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxZVwIUhLn8CRe8t8N1YDJfu3FkvD2UE',
    appId: '1:1015636474486:web:6c20869864fe0550c3fd57',
    messagingSenderId: '1015636474486',
    projectId: 'becure-85720',
    authDomain: 'becure-85720.firebaseapp.com',
    storageBucket: 'becure-85720.firebasestorage.app',
    measurementId: 'G-7M7YWDFEXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4OljLJQTO7pAW6au6Z1tJlFLnwBs5g20',
    appId: '1:1015636474486:android:2699e6cb5f0bdb33c3fd57',
    messagingSenderId: '1015636474486',
    projectId: 'becure-85720',
    storageBucket: 'becure-85720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP7TWM9MsfQ0Fn_a8kAMycKwshdlV74RU',
    appId: '1:1015636474486:ios:f8d99275786c5ffbc3fd57',
    messagingSenderId: '1015636474486',
    projectId: 'becure-85720',
    storageBucket: 'becure-85720.firebasestorage.app',
    iosBundleId: 'com.example.becureProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP7TWM9MsfQ0Fn_a8kAMycKwshdlV74RU',
    appId: '1:1015636474486:ios:f8d99275786c5ffbc3fd57',
    messagingSenderId: '1015636474486',
    projectId: 'becure-85720',
    storageBucket: 'becure-85720.firebasestorage.app',
    iosBundleId: 'com.example.becureProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGxZVwIUhLn8CRe8t8N1YDJfu3FkvD2UE',
    appId: '1:1015636474486:web:d278e50ad95398b7c3fd57',
    messagingSenderId: '1015636474486',
    projectId: 'becure-85720',
    authDomain: 'becure-85720.firebaseapp.com',
    storageBucket: 'becure-85720.firebasestorage.app',
    measurementId: 'G-ECQC59YFSL',
  );
}
